<a href="https://colab.research.google.com/github/paulkarikari/LSTM-sentiment-analysis-with-tensorflow-keras-api/blob/master/sentiment_analysis_tweets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from keras.preprocessing.text import Tokenizer
import pandas as pd

Using TensorFlow backend.


In [0]:
import tensorflow as tf
tf.__version__

'1.15.0'

In [0]:
df= pd.read_csv('Tweets.csv', sep=',')
df.head(10)

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)
5  570300767074181121  ...  Pacific Time (US & Canada)
6  570300616901320704  ...  Pacific Time (US & Canada)
7  570300248553349120  ...  Pacific Time (US & Canada)
8  570299953286942721  ...  Pacific Time (US & Canada)
9  570295459631263746  ...  Eastern Time (US & Canada)

[10 rows x 15 columns]

In [0]:
df[['text','airline_sentiment']].head(10)

text airline_sentiment
0                @VirginAmerica What @dhepburn said.           neutral
1  @VirginAmerica plus you've added commercials t...          positive
2  @VirginAmerica I didn't today... Must mean I n...           neutral
3  @VirginAmerica it's really aggressive to blast...          negative
4  @VirginAmerica and it's a really big bad thing...          negative
5  @VirginAmerica seriously would pay $30 a fligh...          negative
6  @VirginAmerica yes, nearly every time I fly VX...          positive
7  @VirginAmerica Really missed a prime opportuni...           neutral
8    @virginamerica Well, I didn't…but NOW I DO! :-D          positive
9  @VirginAmerica it was amazing, and arrived an ...          positive

In [0]:
tweet_sentiment = df[['text','airline_sentiment']]
tweet_sentiment = df[df['airline_sentiment'] != 'neutral'][['text','airline_sentiment']]

In [0]:
tweet_sentiment.head(10)

text airline_sentiment
1   @VirginAmerica plus you've added commercials t...          positive
3   @VirginAmerica it's really aggressive to blast...          negative
4   @VirginAmerica and it's a really big bad thing...          negative
5   @VirginAmerica seriously would pay $30 a fligh...          negative
6   @VirginAmerica yes, nearly every time I fly VX...          positive
8     @virginamerica Well, I didn't…but NOW I DO! :-D          positive
9   @VirginAmerica it was amazing, and arrived an ...          positive
11  @VirginAmerica I &lt;3 pretty graphics. so muc...          positive
12  @VirginAmerica This is such a great deal! Alre...          positive
13  @VirginAmerica @virginmedia I'm flying your #f...          positive

In [0]:
tweet = tweet_sentiment.text.values

In [0]:
print(tweet[:5])
print(sentiment[:5])

["@VirginAmerica plus you've added commercials to the experience... tacky."
 '@VirginAmerica it\'s really aggressive to blast obnoxious "entertainment" in your guests\' faces &amp; they have little recourse'
 "@VirginAmerica and it's a really big bad thing about it"
 "@VirginAmerica seriously would pay $30 a flight for seats that didn't have this playing.\nit's really the only bad thing about flying VA"
 '@VirginAmerica yes, nearly every time I fly VX this “ear worm” won’t go away :)']
(array([0, 1, 1, ..., 0, 1, 1]), Index(['positive', 'negative'], dtype='object'))


In [0]:
t = Tokenizer(num_words=5000)
t.fit_on_texts(tweet)
vacab_size = len(t.word_index) +1

In [0]:
# summarize what was learned
print('word count',t.word_counts)
print('doc',t.document_count)
print('index',t.word_index)
print('word_docs',t.word_docs)

word count OrderedDict([('virginamerica', 347), ('plus', 46), ("you've", 51), ('added', 14), ('commercials', 5), ('to', 6986), ('the', 5084), ('experience', 197), ('tacky', 1), ("it's", 412), ('really', 283), ('aggressive', 3), ('blast', 2), ('obnoxious', 2), ('entertainment', 22), ('in', 2109), ('your', 1589), ("guests'", 1), ('faces', 2), ('amp', 585), ('they', 610), ('have', 1345), ('little', 58), ('recourse', 5), ('and', 3276), ('a', 3720), ('big', 66), ('bad', 176), ('thing', 58), ('about', 421), ('it', 1541), ('seriously', 78), ('would', 430), ('pay', 115), ('30', 160), ('flight', 3314), ('for', 3383), ('seats', 168), ('that', 1272), ("didn't", 174), ('this', 1182), ('playing', 6), ('only', 290), ('flying', 237), ('va', 7), ('yes', 192), ('nearly', 13), ('every', 107), ('time', 692), ('i', 4236), ('fly', 304), ('vx', 5), ('“ear', 1), ('worm”', 1), ('won’t', 7), ('go', 239), ('away', 64), ('well', 143), ("didn't…but", 1), ('now', 923), ('do', 640), ('d', 15), ('was', 1448), ('amaz

In [0]:
encoded_docs = t.texts_to_sequences(tweet)

In [0]:
from keras.preprocessing.sequence import pad_sequences

In [0]:
padded_sequence = pad_sequences(encoded_docs, maxlen=200)

In [0]:
padded_sequence

array([[   0,    0,    0, ...,    1,    2,  177],
       [   0,    0,    0, ...,   25,  482, 2417],
       [   0,    0,    0, ...,  483,   86,   21],
       ...,
       [   0,    0,    0, ...,    8,    1,  480],
       [   0,    0,    0, ..., 1682,   45,  945],
       [   0,    0,    0, ...,  144,   11, 2325]], dtype=int32)

In [0]:
# Build the model
from keras.models import Sequential
from keras.layers import LSTM,Dense
from keras.layers.embedding import Embedding
from keras.utils.np_utils import to_categorical
embedding_vector_length = 32
model = Sequential() 
model.add(Embedding(vacab_size, embedding_vector_length, input_length=200) )
model.add(LSTM(100)) 
model.add(Dense(1, activation='sigmoid')) 
model.compile(loss='binary_crossentropy',optimizer='adam', metrics=['accuracy']) 
print(model.summary()) 






Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 200, 32)           423488    
_________________________________________________________________
lstm_1 (LSTM)                (None, 100)               53200     
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 101       
Total params: 476,789
Trainable params: 476,789
Non-trainable params: 0
_________________________________________________________________
None


In [0]:
from keras.utils.np_utils import to_categorical

In [0]:
encoded_y = sentiment[0]

In [0]:
print(encoded_y)

[0 1 1 ... 0 1 1]


In [0]:
model.fit(padded_sequence,encoded_y,validation_split=0.2, epochs=10, batch_size=32)




Train on 9232 samples, validate on 2309 samples
Epoch 1/10





9232/9232 [==============================] - 69s 7ms/step - loss: 0.3469 - acc: 0.8554 - val_loss: 0.1675 - val_acc: 0.9376
Epoch 2/10
9232/9232 [==============================] - 68s 7ms/step - loss: 0.1610 - acc: 0.9400 - val_loss: 0.1748 - val_acc: 0.9363
Epoch 3/10
9232/9232 [==============================] - 68s 7ms/step - loss: 0.1072 - acc: 0.9625 - val_loss: 0.2011 - val_acc: 0.9385
Epoch 4/10
9232/9232 [==============================] - 69s 7ms/step - loss: 0.0733 - acc: 0.9750 - val_loss: 0.2204 - val_acc: 0.9294
Epoch 5/10
9232/9232 [==============================] - 68s 7ms/step - loss: 0.0574 - acc: 0.9807 - val_loss: 0.2228 - val_acc: 0.9402
Epoch 6/10
9232/9232 [==============================] - 69s 7ms/step - loss: 0.0443 - acc: 0.9854 - val_loss: 0.2353 - val_acc: 0.9311
Epoch 7/10
9232/9232 [==============================] - 68s 7ms/step - loss: 0.0332 - acc: 0.9898 - val_loss: 0.3248 - val_acc: 0.9307

In [0]:
test_word ="This is soo sad"
tw = t.texts_to_sequences([test_word])
tw

[[29, 14, 731]]

In [0]:
tw = pad_sequences(tw,maxlen=200)
tw

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0

In [0]:
prediction = int(model.predict(tw).round().item())

In [0]:
sentiment[1][prediction]

'negative'

In [0]:
import numpy as np
np.asarray(tweet_sentiment.airline_sentiment)

array(['positive', 'negative', 'negative', ..., 'positive', 'negative',
       'negative'], dtype=object)

In [0]:
model.input

<tf.Tensor 'embedding_1_input:0' shape=(?, 200) dtype=float32>

In [0]:
model.outputs

[<tf.Tensor 'dense_1/Sigmoid:0' shape=(?, 1) dtype=float32>]

In [0]:
{t.name: t for t in model.outputs}

{'dense_1/Sigmoid:0': <tf.Tensor 'dense_1/Sigmoid:0' shape=(?, 1) dtype=float32>}

In [0]:
import tensorflow as tf
import keras
tf.saved_model.simple_save(
        keras.backend.get_session(),
        'model_1',
        inputs={'inputs': model.input},
        outputs={t.name: t for t in model.outputs})


Using TensorFlow backend.


NameError: ignored